USE SchoolManagementDB
GO

CREATE TABLE Lecturers 
(
Id int PRIMARY KEY IDENTITY(1, 1),
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
DateOfBirth Date NOT NULL,
StaffId NVARCHAR(10) NOT NULL UNIQUE
)
GO

DROP TABLE Lecturers

CREATE TABLE Courses
(
    Id INT PRIMARY KEY IDENTITY(1, 1),
    CourseName NVARCHAR(50) NOT NULL,
    CODE NVARCHAR(5) UNIQUE, 
    CREDITS INT NOT NULL 
)
GO